import java.util.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rezaf
 */
public class EquationSolver extends javax.swing.JFrame {
    java.text.DecimalFormat df = new java.text.DecimalFormat("###########.#####################");
    public static void setPosition(int X,int Y){
        Position.setText(X + " , " + Y);
    }
    /**
     * Creates new form EquationSolver
     */
    public EquationSolver() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        La = new javax.swing.JTextField();
        Lb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Qb = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Qa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Qc = new javax.swing.JTextField();
        Lbt = new javax.swing.JButton();
        Qbt = new javax.swing.JButton();
        Qans = new javax.swing.JLabel();
        Lans = new javax.swing.JLabel();
        fcp = new FunctionPainter();
        Drwlinear = new javax.swing.JButton();
        Drwquadratic = new javax.swing.JButton();
        Position = new javax.swing.JLabel();
        prgs = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        PtFdBt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PtFd = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Equation Solver");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Equation Solver");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Linear : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("X + ");

        La.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        La.setText("A");

        Lb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Lb.setText("B");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("= 0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Quadratic : ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("= 0");

        Qb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Qb.setText("B");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("X² + ");

        Qa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Qa.setText("A");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("X²+ ");

        Qc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Qc.setText("C");

        Lbt.setText("Go");
        Lbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LbtActionPerformed(evt);
            }
        });

        Qbt.setText("Go");
        Qbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QbtActionPerformed(evt);
            }
        });

        Qans.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Lans.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        fcp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fcp.setToolTipText("");

        javax.swing.GroupLayout fcpLayout = new javax.swing.GroupLayout(fcp);
        fcp.setLayout(fcpLayout);
        fcpLayout.setHorizontalGroup(
            fcpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );
        fcpLayout.setVerticalGroup(
            fcpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );

        Drwlinear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Drwlinear.setText("Draw");
        Drwlinear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrwlinearActionPerformed(evt);
            }
        });

        Drwquadratic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Drwquadratic.setText("Draw");
        Drwquadratic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrwquadraticActionPerformed(evt);
            }
        });

        Position.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Position.setText(" ");

        prgs.setForeground(new java.awt.Color(255, 255, 255));
        prgs.setToolTipText("");
        prgs.setName(""); // NOI18N
        prgs.setStringPainted(true);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        PtFdBt.setText("Find hit point");
        PtFdBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PtFdBtActionPerformed(evt);
            }
        });

        PtFd.setColumns(20);
        PtFd.setRows(5);
        PtFd.setText("Points");
        jScrollPane1.setViewportView(PtFd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(La, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Lb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(Lbt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Drwlinear))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Qa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Qb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Qc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(Qbt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Drwquadratic)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Qans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(370, 370, 370)
                                .addComponent(jLabel1)
                                .addGap(0, 16, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PtFdBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(prgs, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(Position, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(381, 381, 381))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fcp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(La, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lans, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Drwlinear, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Qa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Qb, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Qc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Qbt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Qans, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Drwquadratic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PtFdBt)
                            .addComponent(prgs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addComponent(Position))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fcp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LbtActionPerformed
        try{
            Lans.setText("Answer =>    x = " + df.format(this.linearEquation(Double.parseDouble(La.getText()), Double.parseDouble(Lb.getText()))));
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Invalid!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LbtActionPerformed

    private void QbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QbtActionPerformed
        try{
            Qans.setText(this.quadraticEQuation(Double.parseDouble(Qa.getText()), Double.parseDouble(Qb.getText()), Double.parseDouble(Qc.getText())));
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Invalid!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_QbtActionPerformed

    private void DrwlinearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrwlinearActionPerformed
        this.linearPointFinder(Double.parseDouble(La.getText()), Double.parseDouble(Lb.getText()));
    }//GEN-LAST:event_DrwlinearActionPerformed

    private void DrwquadraticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrwquadraticActionPerformed
        this.quadraticPointFinder(Double.parseDouble(Qa.getText()), Double.parseDouble(Qb.getText()), Double.parseDouble(Qc.getText()));
    }//GEN-LAST:event_DrwquadraticActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fcp.reset();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PtFdBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PtFdBtActionPerformed
        this.hitFinder(Double.parseDouble(La.getText()), Double.parseDouble(Lb.getText()), Double.parseDouble(Qa.getText()), Double.parseDouble(Qb.getText()), Double.parseDouble(Qc.getText()));
    }//GEN-LAST:event_PtFdBtActionPerformed
    private double linearEquation(double a,double b){
        return -b/a;
    }
    private String quadraticEQuation(double a,double b,double c){
        double delta = b*b - (4*a*c);
        String ans = "";
        if(delta > 0){
           double x1 = (-b + Math.sqrt(delta))/(2*a);
           double x2 = (-b - Math.sqrt(delta))/(2*a);
           ans = String.format("Equation has two answers ==>    x1 = %s , x2 = %s",df.format(x1),df.format(x2));
        }else if (delta == 0){
            double x = -b/2*a;
            ans = String.format("Equation has one answer ==>    x = %s", df.format(x));
        }else{
            ans = "Equation has no answer!";
        }
        
        return ans;
    }
    private void linearPointFinder(double a,double b){
        prgs.setString("Finding and adding the points");
        if(fcp.getFirstTime()){
            fcp.setFirstTime(false);
        }
        for (double i=-350 ; i <=350 ; i += 0.001){
            prgs.setValue((int)i/28000);
            double y = a*i + b;
            fcp.addPoint((int)i, (int)y);
        }
        fcp.repaint();
    }
    private void quadraticPointFinder(double a,double b,double c){
        prgs.setString("Finding and adding the points");
        if(fcp.getFirstTime()){
            fcp.setFirstTime(false);
        }
        for (double i=-350 ; i <=350 ; i += 0.001) {
            prgs.setValue((int)i/14000);
            double y = a*i*i + b*i + c;
            fcp.addPoint((int)i, (int)y);
        }
        fcp.repaint();
    }
    public final static void setPrgsText(String s){
        prgs.setString(s);
    }
    public final static void setPrgsInt(double d){
        double r = 50 + d;
        prgs.setValue((int)r);
    }
    private void hitFinder(double La,double Lb,double Qa,double Qb,double Qc){
        ArrayList<Double> Xs = new ArrayList();
        ArrayList<Double> Ys = new ArrayList();
        for (double i = -350 ; i <= 350 ; i += 0.001){
            double y1 = La*i + Lb;
            double y2 = Qa*i*i + Qb*i + Qc;
            //System.out.printf("%f , %f , %f\n",y1,y2,i);
            if(Double.compare(y1, y2)==0){
                Xs.add(i);
                Ys.add(y1);
            }
        }
        if(Xs.isEmpty()){
            PtFd.setText("There are no hit points!\n----------------------\nSorry!");
        }else{
            String points = "";
            for (int i = 0; i < Xs.size(); i++) {
                points += String.format("%f , %f", Xs.get(i),Ys.get(i));
            }
            PtFd.setText("We found " + Xs.size()  + " points!\n" + "----------------------\n" + points);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EquationSolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EquationSolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EquationSolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EquationSolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EquationSolver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Drwlinear;
    private javax.swing.JButton Drwquadratic;
    private javax.swing.JTextField La;
    private javax.swing.JLabel Lans;
    private javax.swing.JTextField Lb;
    private javax.swing.JButton Lbt;
    private static javax.swing.JLabel Position;
    private javax.swing.JTextArea PtFd;
    private javax.swing.JButton PtFdBt;
    private javax.swing.JTextField Qa;
    private javax.swing.JLabel Qans;
    private javax.swing.JTextField Qb;
    private javax.swing.JButton Qbt;
    private javax.swing.JTextField Qc;
    private FunctionPainter fcp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JProgressBar prgs;
    // End of variables declaration//GEN-END:variables
}
