import java.awt.*;
import java.util.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rezaf
 */
public class FunctionPainter extends javax.swing.JPanel {
    private ArrayList<Integer> Xc = new ArrayList();
    private ArrayList<Integer> Yc = new ArrayList();
    private boolean FirstTime = true;
    
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        g.drawLine(this.getWidth()/2,0,this.getWidth()/2,this.getHeight());
        g.drawLine(0, this.getHeight()/2, this.getWidth(), this.getHeight()/2);
        g.drawLine(this.getWidth()/2, 0, this.getWidth()/2-10, 10);
        g.drawLine(this.getWidth()/2, 0, this.getWidth()/2+10, 10);
        g.drawLine(this.getWidth(), this.getHeight()/2, this.getWidth()-10, this.getHeight()/2-10);
        g.drawLine(this.getWidth(), this.getHeight()/2, this.getWidth()-10, this.getHeight()/2+10);
        if (!FirstTime){
            EquationSolver.setPrgsText("Drawing POints");
        for (int i = 0 ; i < Xc.size() ; i++){
            g.fillOval(Xc.get(i), Yc.get(i), 2, 2);
            EquationSolver.setPrgsInt(i/14000);
        }
        EquationSolver.setPrgsText("Done!");
        }
    }
    /**
     * Creates new form FunctionPainter
     */
    public FunctionPainter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        int x = evt.getX()-this.getWidth()/2;
        int y = -(evt.getY()-this.getHeight()/2);
        EquationSolver.setPosition(x, y);
    }//GEN-LAST:event_formMouseMoved
    public final void addPoint(int x,int y){
        int x1 = x+this.getWidth()/2;
        int y1 = -(y-this.getHeight()/2);
        Xc.add(x1);
        Yc.add(y1);
        
    }
    public final void setFirstTime(boolean b){
        this.FirstTime = b;
    }
    public final boolean getFirstTime(){
        return this.FirstTime;
    }
    //reset the entire drawing page.
    public final void reset(){
        this.Xc.clear();
        this.Yc.clear();
        this.repaint();
    } 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
