
import java.awt.event.ActionEvent;
import java.text.DecimalFormat;
import java.util.*;
import java.text.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sako
 */
public class Main extends javax.swing.JFrame {
    private String hstt;
    private String rsltt;
    private static Date dt =  new Date();
    private static SimpleDateFormat dfd = new SimpleDateFormat("E dd/MM/yyyy");
    private final DecimalFormat df = new DecimalFormat("######################.#####################################################");
    private void reSetH(){
        this.hstt = "";
    }
    private void reSetR(){
        this.rsltt= "";
    }
    

    /**
     * Creates new form Main
     */
    public Main() {
        
        this.reSetH();
        this.reSetR();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hst = new javax.swing.JLabel();
        rslt = new javax.swing.JLabel();
        n1 = new javax.swing.JButton();
        n4 = new javax.swing.JButton();
        n5 = new javax.swing.JButton();
        n2 = new javax.swing.JButton();
        n3 = new javax.swing.JButton();
        n6 = new javax.swing.JButton();
        n7 = new javax.swing.JButton();
        n8 = new javax.swing.JButton();
        n9 = new javax.swing.JButton();
        n0 = new javax.swing.JButton();
        Mlt = new javax.swing.JButton();
        Dvd = new javax.swing.JButton();
        Sum = new javax.swing.JButton();
        Min = new javax.swing.JButton();
        Eq = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        n10 = new javax.swing.JButton();
        Bsc = new javax.swing.JButton();
        Sgn = new javax.swing.JButton();
        n11 = new javax.swing.JButton();
        n12 = new javax.swing.JButton();
        n13 = new javax.swing.JButton();
        n14 = new javax.swing.JButton();
        n15 = new javax.swing.JButton();
        n16 = new javax.swing.JButton();
        n17 = new javax.swing.JButton();
        n18 = new javax.swing.JButton();
        Dtsh = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("i love you Panti");
        setLocationByPlatform(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        hst.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hst.setText("History");
        hst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        rslt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rslt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rslt.setText("0");
        rslt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hst, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rslt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(hst, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rslt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        n1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n1.setMnemonic('1');
        n1.setText("1");
        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });
        n1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        n4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n4.setMnemonic('4');
        n4.setText("4");
        n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n4ActionPerformed(evt);
            }
        });
        n4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        n5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n5.setMnemonic('5');
        n5.setText("5");
        n5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n5ActionPerformed(evt);
            }
        });
        n5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        n2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n2.setMnemonic('2');
        n2.setText("2");
        n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2ActionPerformed(evt);
            }
        });
        n2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        n3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n3.setMnemonic('3');
        n3.setText("3");
        n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n3ActionPerformed(evt);
            }
        });
        n3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        n6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n6.setMnemonic('6');
        n6.setText("6");
        n6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n6ActionPerformed(evt);
            }
        });
        n6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        n7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n7.setMnemonic('7');
        n7.setText("7");
        n7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n7ActionPerformed(evt);
            }
        });
        n7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        n8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n8.setMnemonic('8');
        n8.setText("8");
        n8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n8ActionPerformed(evt);
            }
        });
        n8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        n9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n9.setMnemonic('9');
        n9.setText("9");
        n9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n9ActionPerformed(evt);
            }
        });
        n9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        n0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n0.setMnemonic('0');
        n0.setText("0");
        n0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n0ActionPerformed(evt);
            }
        });
        n0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        Mlt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Mlt.setText("×");
        Mlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MltActionPerformed(evt);
            }
        });
        Mlt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        Dvd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Dvd.setMnemonic('/');
        Dvd.setText("÷");
        Dvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DvdActionPerformed(evt);
            }
        });
        Dvd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        Sum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sum.setText("+");
        Sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumActionPerformed(evt);
            }
        });
        Sum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        Min.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Min.setText("-");
        Min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinActionPerformed(evt);
            }
        });
        Min.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        Eq.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Eq.setText("=");
        Eq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqActionPerformed(evt);
            }
        });
        Eq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        Clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clear.setMnemonic('c');
        Clear.setText("CLEAR");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        Clear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        n10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n10.setMnemonic('3');
        n10.setText(".");
        n10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n10ActionPerformed(evt);
            }
        });
        n10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        Bsc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bsc.setMnemonic('c');
        Bsc.setText("<");
        Bsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BscActionPerformed(evt);
            }
        });
        Bsc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        Sgn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sgn.setText("±");
        Sgn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SgnActionPerformed(evt);
            }
        });
        Sgn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        n11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        n11.setMnemonic('7');
        n11.setText("M-");
        n11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n11ActionPerformed(evt);
            }
        });
        n11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        n12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        n12.setMnemonic('7');
        n12.setText("M+");
        n12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n12ActionPerformed(evt);
            }
        });
        n12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        n13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        n13.setMnemonic('7');
        n13.setText("MC");
        n13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n13ActionPerformed(evt);
            }
        });
        n13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        n14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        n14.setMnemonic('7');
        n14.setText("MR");
        n14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n14ActionPerformed(evt);
            }
        });
        n14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        n15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        n15.setText("%");
        n15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n15ActionPerformed(evt);
            }
        });

        n16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n16.setText("√");
        n16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n16ActionPerformed(evt);
            }
        });

        n17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        n17.setText("x²");
        n17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n17ActionPerformed(evt);
            }
        });

        n18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        n18.setText("01");
        n18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n18ActionPerformed(evt);
            }
        });

        Dtsh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Dtsh.setText(getDate());

        jButton1.setText("Equation solver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(n5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(n6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Sgn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(n0, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(n10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(n12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(n13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(n7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(n8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(n9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(n16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Dvd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Sum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(Min, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Mlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Eq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Bsc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(n17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Dtsh, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(n11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(n14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(n15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(n18, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dtsh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(n7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(n8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(n9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mlt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dvd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bsc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n0, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Min, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sgn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Eq, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void n0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n0ActionPerformed
        if(!rslt.getText().equals("0")){
            rslt.setText(this.rsltt + "0");
            this.rsltt = rslt.getText();
            hst.setText(hstt);
        }
    }//GEN-LAST:event_n0ActionPerformed

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
       rslt.setText(this.rsltt + "1");
        this.rsltt = rslt.getText();
       hst.setText(hstt);
    }//GEN-LAST:event_n1ActionPerformed

    private void n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2ActionPerformed
        rslt.setText(this.rsltt + "2");
        this.rsltt = rslt.getText();
        hst.setText(hstt);
    }//GEN-LAST:event_n2ActionPerformed

    private void n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n3ActionPerformed
        rslt.setText(this.rsltt + "3");
        this.rsltt = rslt.getText();
        hst.setText(hstt);
    }//GEN-LAST:event_n3ActionPerformed

    private void n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n4ActionPerformed
        rslt.setText(this.rsltt + "4");
        this.rsltt = rslt.getText();
        hst.setText(hstt);
    }//GEN-LAST:event_n4ActionPerformed

    private void n5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n5ActionPerformed
        rslt.setText(this.rsltt + "5");
        this.rsltt = rslt.getText();
        hst.setText(hstt);
    }//GEN-LAST:event_n5ActionPerformed

    private void n6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n6ActionPerformed
        rslt.setText(this.rsltt + "6");
        this.rsltt = rslt.getText();
        hst.setText(hstt);
    }//GEN-LAST:event_n6ActionPerformed

    private void n7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n7ActionPerformed
        rslt.setText(this.rsltt + "7");
        this.rsltt = rslt.getText();
        hst.setText(hstt);
    }//GEN-LAST:event_n7ActionPerformed

    private void n8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n8ActionPerformed
        rslt.setText(this.rsltt + "8");
        this.rsltt = rslt.getText();
        hst.setText(hstt);
    }//GEN-LAST:event_n8ActionPerformed

    private void n9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n9ActionPerformed
        rslt.setText(this.rsltt + "9");
        this.rsltt = rslt.getText();
        hst.setText(hstt);
    }//GEN-LAST:event_n9ActionPerformed

    private void MinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinActionPerformed
        Clc.F.add(2);
        Clc.N.add(Double.parseDouble(rslt.getText().trim()));
        hstt = this.hstt + rslt.getText() + " - ";
        hst.setText(hstt);
        this.reSetR();
    }//GEN-LAST:event_MinActionPerformed

    private void SumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumActionPerformed
        Clc.F.add(1);
        Clc.N.add(Double.parseDouble(rslt.getText().trim()));
        hstt = this.hstt + rslt.getText() + " + ";
        hst.setText(hstt);
        this.reSetR();
        
    }//GEN-LAST:event_SumActionPerformed

    private void DvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DvdActionPerformed
        Clc.F.add(4);
        Clc.N.add(Double.parseDouble(rslt.getText().trim()));
        hstt = this.hstt + rslt.getText() + " / ";
        hst.setText(hstt);
        this.reSetR();
    }//GEN-LAST:event_DvdActionPerformed

    private void MltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MltActionPerformed
        Clc.F.add(3);
        Clc.N.add(Double.parseDouble(rslt.getText().trim()));
        hstt = this.hstt + rslt.getText() + " x ";
        hst.setText(hstt);
        this.reSetR();
    }//GEN-LAST:event_MltActionPerformed

    private void EqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqActionPerformed
        if(Clc.F.size() == 1){
            if(rslt.getText().isEmpty())
                Clc.N.add(Clc.N.get(0));
        }
        Clc.N.add(Double.parseDouble(rslt.getText().trim()));
        hstt = this.hstt + rslt.getText() + " = ";
        rslt.setText(String.format("%s",df.format(Clc.Hdl())));
        hst.setText(hstt);
        Clc.F.clear();
        Clc.N.clear();
        this.reSetH();
        this.reSetR();
    }//GEN-LAST:event_EqActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        Clc.F.clear();
        Clc.N.clear();
        hst.setText(hstt + rslt.getText());
        rslt.setText("0");
        this.reSetH();
        this.reSetR();
    }//GEN-LAST:event_ClearActionPerformed

    private void n10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n10ActionPerformed
        if(!rslt.getText().contains(".") && !rsltt.isEmpty()){
            rslt.setText(this.rsltt + ".");
            this.rsltt = rslt.getText();
            hst.setText(hstt);
        }
    }//GEN-LAST:event_n10ActionPerformed

    private void BscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BscActionPerformed
        if(rslt.getText().length()>1){
            rslt.setText(rslt.getText().substring(0, rslt.getText().length()-1));
            rsltt = rslt.getText();
        }
        else {
            rsltt = "";
            rslt.setText("0");
        }
    }//GEN-LAST:event_BscActionPerformed

    private void SgnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SgnActionPerformed
        if(!(rslt.getText().equals("0") || rslt.getText().isEmpty())) {
            if(Double.parseDouble(rslt.getText()) > 0) rslt.setText("-" + rslt.getText());
            else rslt.setText(rslt.getText().substring(1, rslt.getText().length()));
            
        }
    }//GEN-LAST:event_SgnActionPerformed
    ActionEvent ext;
    private void KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeyTyped
        switch (evt.getKeyChar()){
            case '0' :
                n0ActionPerformed(ext);
                break;
            case '1' :
                n1ActionPerformed(ext);
                break;
            case '2' :
                n2ActionPerformed(ext);
                break;
            case '3' :
                n3ActionPerformed(ext);
                break;
            case '4' :
                n4ActionPerformed(ext);
                break;
            case '5' :
                n5ActionPerformed(ext);
                break;
            case '6' :
                n6ActionPerformed(ext);
                break;
            case '7' :
                n7ActionPerformed(ext);
                break;
            case '8' :
                n8ActionPerformed(ext);
                break;
            case '9' :
                n9ActionPerformed(ext);
                break;
            case '.' : 
                n10ActionPerformed(ext);
                break;
        }
    }//GEN-LAST:event_KeyTyped

    private void n11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n11ActionPerformed
        Clc.MMinus.add(Double.parseDouble(rslt.getText().trim()));
        rsltt = "";
        rslt.setText("0");
    }//GEN-LAST:event_n11ActionPerformed

    private void n12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n12ActionPerformed
        Clc.MPlus.add(Double.parseDouble(rslt.getText().trim()));
        rsltt = "";
        rslt.setText("0");
    }//GEN-LAST:event_n12ActionPerformed

    private void n13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n13ActionPerformed
        Clc.MPlus.clear();
        Clc.MMinus.clear();
    }//GEN-LAST:event_n13ActionPerformed

    private void n14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n14ActionPerformed
        rslt.setText(df.format(Clc.memoryResault()));
    }//GEN-LAST:event_n14ActionPerformed

    private void n15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n15ActionPerformed
        rslt.setText(String.format("%s", df.format(Double.parseDouble(rslt.getText())/100)));
    }//GEN-LAST:event_n15ActionPerformed

    private void n16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n16ActionPerformed
        hstt = "√" + rslt.getText() + " = ";
        hst.setText(hstt);
        rslt.setText(String.format("%s", df.format(Math.sqrt(Double.parseDouble(rslt.getText())))));
        this.reSetH();
    }//GEN-LAST:event_n16ActionPerformed

    private void n17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n17ActionPerformed
        double x = Double.parseDouble(rslt.getText().trim());
        hst.setText(rslt.getText() + "² = ");
        rslt.setText(String.format("%s",df.format(x*x)));
        this.reSetR();
        
    }//GEN-LAST:event_n17ActionPerformed

    private void n18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n18ActionPerformed
        hst.setText(Math.round(Double.parseDouble(rslt.getText())) + " to binary = ");
        rslt.setText(Long.toBinaryString(Math.round(Double.parseDouble(rslt.getText()))));
        this.reSetR();
    }//GEN-LAST:event_n18ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EquationSolver eq = new EquationSolver();
        eq.setVisible(true);
        eq.setDefaultCloseOperation(2);
        eq.setLocation(this.getLocation());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }
    private String getDate(){
        String date;
        while(true){
            date = dfd.format(dt);
            return date;
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bsc;
    private javax.swing.JButton Clear;
    private javax.swing.JLabel Dtsh;
    private javax.swing.JButton Dvd;
    private javax.swing.JButton Eq;
    private javax.swing.JButton Min;
    private javax.swing.JButton Mlt;
    private javax.swing.JButton Sgn;
    private javax.swing.JButton Sum;
    private javax.swing.JLabel hst;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton n0;
    private javax.swing.JButton n1;
    private javax.swing.JButton n10;
    private javax.swing.JButton n11;
    private javax.swing.JButton n12;
    private javax.swing.JButton n13;
    private javax.swing.JButton n14;
    private javax.swing.JButton n15;
    private javax.swing.JButton n16;
    private javax.swing.JButton n17;
    private javax.swing.JButton n18;
    private javax.swing.JButton n2;
    private javax.swing.JButton n3;
    private javax.swing.JButton n4;
    private javax.swing.JButton n5;
    private javax.swing.JButton n6;
    private javax.swing.JButton n7;
    private javax.swing.JButton n8;
    private javax.swing.JButton n9;
    private javax.swing.JLabel rslt;
    // End of variables declaration//GEN-END:variables
}
